image: golang:1.12

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/gitlab.com
    - /go/src/gopkg.in

stages:
  - test

before_script:
  - go get ./...

unit_tests:
  stage: test
  script:
    - go test ./...
